name: flutter_lyc
description: Flutter LYC Application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^6.0.0
  shared_preferences: ^0.4.1
  xbanner: ^0.0.3
  flutter_search_bar: ^2.0.3
  material_search: ^0.2.7
  search_bar: ^1.0.1
  url_launcher: ^3.0.1
  image_picker: ^0.4.5
  http: ^0.11.3+16
  json_annotation: ^0.2.5
  html2md: ^0.1.5
  flutter_markdown: ^0.1.5
  flutter_facebook_login: ^1.1.1
  intl: ^0.15.6
  share: ^0.5.2
  small_calendar: ^0.4.0
  path_provider: ^0.4.1
  image: ^2.0.4
  #pusher_flutter: ^0.0.5
  chewie: ^0.6.1
  flutter_webview_plugin: ^0.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/lyc.png
  - assets/videos/1.mp4
  - assets/images/male_doctor.png
  - assets/images/female_doctor.png
  - assets/images/lyc_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Zawgyi-One
      fonts:
        - asset: fonts/Zawgyi-One-20060620.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
